### ISSUE TITLE
advise endpoint seems to be broken

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#1091]
**Describe the bug**
```
    When thamos advise is run for flask_py36 for recommendation type LATEST asynchronously # features/steps/basic.py:58 1.158s
      Traceback (most recent call last):
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/basic.py", line 85, in thamos_advise
          debug=True,
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/lib.py", line 89, in wrapper
          result = func(api_client, *args, **kwargs)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/lib.py", line 367, in advise
          response = api_instance.post_advise_python(advise_input, **parameters)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 434, in post_advise_python
          (data) = self.post_advise_python_with_http_info(body, recommendation_type, **kwargs)  # noqa: E501
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 554, in post_advise_python_with_http_info
          collection_formats=collection_formats)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 321, in call_api
          _preload_content, _request_timeout)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 152, in __call_api
          _request_timeout=_request_timeout)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 364, in request
          body=body)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/rest.py", line 274, in POST
          body=body)
        File "/home/goern/.local/share/virtualenvs/integration-tests-Me6nOCO7/lib/python3.6/site-packages/thamos/swagger_client/rest.py", line 227, in request
          raise ApiException(http_resp=r)
      thamos.swagger_client.rest.ApiException: (400)
      Reason: BAD REQUEST
      HTTP response headers: HTTPHeaderDict({'Server': 'gunicorn/20.0.4', 'Date': 'Wed, 29 Jul 2020 14:57:59 GMT', 'Content-Type': 'application/problem+json', 'Content-Length': '335', 'Access-Control-Allow-Origin': '*', 'X-Thoth-Version': '0.6.8', 'Set-Cookie': '99ca826347b0162a0aa474189c69e824=8746cee1f75e7e5a9aa4ea9eb9ec2b55; path=/; HttpOnly; Secure'})
      HTTP response body: {
        "detail": "'None' is not one of ['cli', 's2i', 'github_app', 'kebechet', 'jupyter_notebook']\n\nFailed validating 'enum' in schema:\n    {'enum': ['cli', 's2i', 'github_app', 'kebechet', 'jupyter_notebook'],\n     'type': 'string'}\n\nOn instance:\n    'None'",
        "status": 400,
        "title": "Bad Request",
        "type": "about:blank"
      }
      
```

**To Reproduce**
run the integration-tests

**Expected behavior**
`Feature: Running thamos advise against deployment # features/thamos_advise.feature:1` should succeed 

/king bug
/assign @fridex 
/priority critical-urgent

**Comment by fridex** [comment]
Should be nullable...
