### ISSUE TITLE
thamos advise errors out on example...

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#1517]
**Describe the bug**

**To Reproduce**
1. use https://github.com/thoth-station/thamos/tree/master/examples/scoring
2. use `toolbox enter thoth-toolbox-v0.5.4`
3. `cd examples/scoring`
4. `thamos advise --force`

```
2020-10-30 09:47:31,557 [338145] CRITICAL root: Traceback (most recent call last):
  File "/usr/local/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/thamos/cli.py", line 464, in advise
    _write_files(pipfile, pipfile_lock, configuration.requirements_format)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/thamos/cli.py", line 109, in _write_files
    project = Project.from_dict(requirements, requirements_lock)
  File "/usr/local/lib/python3.8/site-packages/thoth/python/project.py", line 117, in from_dict
    pipfile_lock=PipfileLock.from_dict(pipfile_lock, pipfile=pipfile),
  File "/usr/local/lib/python3.8/site-packages/thoth/python/pipfile.py", line 428, in from_dict
    packages=Packages.from_pipfile_lock(dict_["default"], develop=False, meta=meta),
  File "/usr/local/lib/python3.8/site-packages/thoth/python/packages.py", line 99, in from_pipfile_lock
    package_version[package_name] = PackageVersion.from_pipfile_lock_entry(
  File "/usr/local/lib/python3.8/site-packages/thoth/python/package_version.py", line 211, in from_pipfile_lock_entry
    raise PipfileParseError(
thoth.python.exceptions.PipfileParseError: Package intel-tensorflow has missing or empty configuration in the locked entry: {'hashes': [], 'index': 'pypi-org', 'version': '==2.0.0'}
```

**Additional context**
```
Thamos Client version: 1.0.1
Thoth API https://khemenu.thoth-station.ninja/api/v1: 0.6.20
```

**Comment by fridex** [comment]
Not sure what went wrong. I've rescheduled solver for `intel-tensorflow==2.0.0`:

```json
{
  "analysis_id": [
    "solver-rhel-8-py36-4b16d880"
  ],
  "cached": false,
  "parameters": {
    "debug": false,
    "indexes": [
      "https://tensorflow.pypi.thoth-station.ninja/index/rhel7.7/AVX2/simple",
      "https://tensorflow.pypi.thoth-station.ninja/index/rhel7.6/AVX2/simple",
      "https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple",
      "https://tensorflow.pypi.thoth-station.ninja/index/rhel7.5/AVX2/simple",
      "https://pypi.org/simple"
    ],
    "packages": "intel-tensorflow==2.0.0",
    "transitive": false
  }
}
```

**Comment by fridex** [comment]
Looks like no longer relevant. I've triggered advice for this stack. It successfully finished. See:

   https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-2f7f4a7b

Closing this issue, feel free to reopen if the issue persists.
