### ISSUE TITLE
'NoneType' object is not subscriptable in TensorFlow API sieve

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1579]
**Describe the bug**

```
Traceback (most recent call last):
  File "/opt/app-root/src/thoth/adviser/run.py", line 76, in subprocess_run
    with_devel=with_devel, user_stack_scoring=user_stack_scoring
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1292, in resolve
    for state in self._do_resolve_states(with_devel=with_devel, user_stack_scoring=user_stack_scoring):
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1223, in _do_resolve_states
    with_devel=with_devel, user_stack_scoring=user_stack_scoring
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1128, in _do_resolve_states_raw
    state = self._prepare_initial_state(with_devel=with_devel)
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 719, in _prepare_initial_state
    package_versions = list(self._run_sieves(package_versions))
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 303, in _run_sieves
    yield from result
  File "/opt/app-root/src/thoth/adviser/sieves/solved.py", line 72, in run
    for package_version in package_versions:
  File "/opt/app-root/src/thoth/adviser/sieves/index_enabled.py", line 56, in run
    for package_version in package_versions:
  File "/opt/app-root/src/thoth/adviser/sieves/locked.py", line 62, in run
    for package_version in package_versions:
  File "/opt/app-root/src/thoth/adviser/sieves/prereleases.py", line 58, in run
    for package_version in package_versions:
  File "/opt/app-root/src/thoth/adviser/sieves/tensorflow/tf_api.py", line 121, in run
    version = ".".join(map(str, package_version.semantic_version.release[:2]))
TypeError: 'NoneType' object is not subscriptable
```

**To Reproduce**
1. Run advise on a tensorflow stack with API usage
2. See the error

**Expected behavior**

Advise should be computed.

**Comment by goern** [comment]
@fridex do you take care about this?

/kind bug

**Comment by fridex** [comment]
Yes, trying to reproduce it locally.

**Comment by fridex** [comment]
Haven't seen this, also not reproduced. I think it's safe to close this, we can reopen if the issue arises (maybe it was part of some testing in the cluster).
