### ISSUE TITLE
module 'thoth.adviser.boots' has no attribute 'VersionClashBoot'

### ISSUE THREAD

**Issue by harshad16** [thoth-station/adviser#1712]
**Describe the bug**
Dependency monkey run is failing with following error:

thoth.adviser.exceptions.UnknownPipelineUnitError: Cannot import unit VersionClashBoot: module 'thoth.adviser.boots' has no attribute 'VersionClashBoot'
```
{"name": "thoth.adviser", "levelname": "INFO", "module": "thoth-adviser", "lineno": 202, "funcname": "cli", "created": 1614719241.061411, "asctime": "2021-03-02 21:07:21,061", "msecs": 61.41090393066406, "relative_created": 2584.578037261963, "process": 1, "message": "Version: 0.25.1"}
Traceback (most recent call last):
  File "/opt/app-root/src/thoth/adviser/pipeline_builder.py", line 349, in _do_instantiate_from_dict
    unit_class = getattr(module, configuration_entry["name"])
AttributeError: module 'thoth.adviser.boots' has no attribute 'VersionClashBoot'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "thoth-adviser", line 793, in <module>
    __name__ == "__main__" and cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
{"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 222, "funcname": "_send_event", "created": 1614719241.441213, "asctime": "2021-03-02 21:07:21,441", "msecs": 441.21289253234863, "relative_created": 2964.3800258636475, "process": 1, "message": "Sending event, type:null level:error event_id:399e2f7c9de34a1980308d859eb3c06e project:1298083 host:sentry.io"}
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "thoth-adviser", line 722, in dependency_monkey
    pipeline_config = None if pipeline is None else PipelineBuilder.load(pipeline)
  File "/opt/app-root/src/thoth/adviser/pipeline_builder.py", line 445, in load
    return cls.from_dict(yaml.safe_load(config))
  File "/opt/app-root/src/thoth/adviser/pipeline_builder.py", line 379, in from_dict
    boot_unit: Boot = cls._do_instantiate_from_dict(thoth.adviser.boots, boot_entry)  # type: ignore
  File "/opt/app-root/src/thoth/adviser/pipeline_builder.py", line 351, in _do_instantiate_from_dict
    raise UnknownPipelineUnitError(f"Cannot import unit {configuration_entry['name']}: {str(exc)}") from exc
```

**To Reproduce**
1. Go to https://management.moc.thoth-station.ninja/
2. Execute the POST  requests `/dependency-monkey/python` with the default spec 
3. Head to the moc cluster , namespace thoth-amun-inspection-prod
4. See error in the log of the pod

**Image version** : v0.25.1

**Comment by fridex** [comment]
You can remove the following entry in the example input:

```
      {
        "configuration": {},
        "name": "VersionClashBoot"
      }
```

The example should work after that.
