### ISSUE TITLE
Provenance checks should report back errors when VCS is used

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#192]
If a user uses a package from VCS, we fail with a back-trace as attached. Instead of error-ing out, we should probably fail with a report stating VCS is not possible (especially in gating in CI systems).

```
2019-03-06 15:14:33,573 [31189] INFO     root:126: Logging to a Sentry instance is turned off
2019-03-06 15:14:33,573 [31189] INFO     root:148: Logging to rsyslog endpoint is turned off
2019-03-06 15:14:33,592 [31189] INFO     __main__:119: Version: 0.3.0
2019-03-06 15:14:33,645 [31189] CRITICAL root:111: Traceback (most recent call last):
  File "/home/fpokorny/github.com/thoth-station/adviser/thoth-adviser", line 581, in <module>
    cli()
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fpokorny/github.com/thoth-station/adviser/thoth-adviser", line 187, in provenance
    project = _instantiate_project(requirements, requirements_locked, files)
  File "/home/fpokorny/github.com/thoth-station/adviser/thoth-adviser", line 76, in _instantiate_project
    pipfile = Pipfile.from_string(requirements)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/thoth/python/pipfile.py", line 272, in from_string
    return cls.from_dict(parsed)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/thoth/python/pipfile.py", line 284, in from_dict
    packages=Packages.from_pipfile(packages, develop=False, meta=meta),
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/thoth/python/packages.py", line 95, in from_pipfile
    meta
  File "/home/fpokorny/.local/share/virtualenvs/adviser-OKwQWmcF/lib/python3.6/site-packages/thoth/python/package_version.py", line 267, in from_pipfile_entry
    f"Package {package_name} uses a version control system instead of package index: {entry}"
thoth.python.exceptions.UnsupportedConfiguration: Package thoth-storages uses a version control system instead of package index: {'git': 'https://github.com/thoth-station/storages'}
```

**Comment by saisankargochhayat** [comment]
@fridex  How do I replicate this error?
`./thoth-adviser provenance -r=$(cat ./Pipfile) -l=$(cat ./Pipfile.lock)`
Provenance seems to expect strings.

**Comment by fridex** [comment]
Add a dependency that is installed from a git repo instead of PyPI.

**Comment by saisankargochhayat** [comment]
How do we error out with a report? Just catch the type of error in the calling method in the advisor cli in a similar manner to this - [[link](https://github.com/thoth-station/adviser/blob/accea0cfb9a5cabf54a755ba8a049d17f91331ed/thoth/adviser/cli.py#L230)]?
https://github.com/thoth-station/python/blob/eda4af0686f438baf210913670e713172035f59a/thoth/python/package_version.py#L257

**Comment by fridex** [comment]
> How do we error out with a report? Just catch the type of error in the calling method in the advisor cli in a similar manner to this - [[link](https://github.com/thoth-station/adviser/blob/accea0cfb9a5cabf54a755ba8a049d17f91331ed/thoth/adviser/cli.py#L230)]?

Yes.
