### ISSUE TITLE
packaging.version.InvalidVersion: Invalid version: 'None'

### ISSUE THREAD

**Issue by harshad16** [thoth-station/adviser#2394]
## Bug description

Adviser run fails with following error messgae:
```
Traceback (most recent call last):
  File "thoth-adviser", line 1011, in <module>
    __name__ == "__main__" and cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "thoth-adviser", line 617, in advise
    resolver = Resolver.get_adviser_instance(
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1482, in get_adviser_instance
    pipeline = PipelineBuilder.get_adviser_pipeline_config(
  File "/opt/app-root/src/thoth/adviser/pipeline_builder.py", line 520, in get_adviser_pipeline_config
    return cls._build_configuration(
  File "/opt/app-root/src/thoth/adviser/pipeline_builder.py", line 354, in _build_configuration
    for unit_configuration in unit_class.should_include(ctx):
  File "/opt/app-root/src/thoth/adviser/prescription/v1/boot.py", line 82, in should_include
    if cls._should_include_base(builder_context):
  File "/opt/app-root/src/thoth/adviser/prescription/v1/unit.py", line 279, in _should_include_base
    if not cls._should_include_base_cached(unit_name, builder_context, should_include_dict):
  File "/opt/app-root/src/thoth/adviser/prescription/v1/unit_cache.py", line 54, in wrapped
    result: bool = func(cls, unit_name, pipeline_builder, should_include_dict)
  File "/opt/app-root/src/thoth/adviser/prescription/v1/unit.py", line 516, in _should_include_base_cached
    if not cls._check_version(runtime_used.cuda_version, cuda_version_spec):
  File "/opt/app-root/src/thoth/adviser/prescription/v1/unit.py", line 264, in _check_version
    return Version(version_present) in SpecifierSet(version_spec_declared)
  File "/opt/app-root/lib64/python3.8/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'
```

[adviser-221025161456-97e60985f358245e-2588813409-main.log](https://github.com/thoth-station/adviser/files/9862158/adviser-221025161456-97e60985f358245e-2588813409-main.log)

**Comment by goern** [comment]
replicater:

```
cd $(mktemp -d)
pipenv install nltk
thamos config # reconfigure to use ubi8-py3.8
thamos advise # will fail
# remove all configs with `null` from .thoth.yaml
thamos advise # will work
```

**Comment by harshad16** [comment]
The single quote are at the discover cuda
https://github.com/thoth-station/thamos/blob/eda365d1d61489453d4951c5a7d02c06e5f27649/thamos/config.py#L329

create the result as 
`cuda_version: 'None'`
which is not treated as None , instead as str None.
that is the reason for failer in adviser.
