### ISSUE TITLE
Prescription build is failing adviser release

### ISSUE THREAD

**Issue by harshad16** [thoth-station/adviser#2402]
Prescription build is failing adviser release.
Logs:
```
{"name": "thoth.adviser.prescription.v1.prescription", "levelname": "ERROR", "module": "prescription", "lineno": 302, "funcname": "load", "created": 1670231438.3877933, "asctime": "2022-12-05 09:10:38,387", "msecs": 387.79330253601074, "relative_created": 2576.369047164917, "process": 1565, "message": "Failed to load prescription from '\''prescriptions/fs/gh_link.yaml'\''"}
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/adviser/prescription/v1/prescription.py", line 197, in from_dict
    PRESCRIPTION_SCHEMA(prescription)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['\''units'\'']['\''wraps'\''][0]['\''run'\'']['\''justification'\''][0]['\''metadata'\'']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/bin/thoth-adviser", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/adviser/cli.py", line 979, in validate_prescription
    prescription = Prescription.validate(prescriptions)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/adviser/prescription/v1/prescription.py", line 116, in validate
    prescription_instance = cls.load(prescriptions)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/adviser/prescription/v1/prescription.py", line 295, in load
    prescription_instance = cls.from_dict(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/adviser/prescription/v1/prescription.py", line 203, in from_dict
    raise PrescriptionSchemaError(str(exc))
thoth.adviser.exceptions.PrescriptionSchemaError: extra keys not allowed @ data['\''units'\'']['\''wraps'\''][0]['\''run'\'']['\''justification'\''][0]['\''metadata'\'']
subprocess exited with status 1
subprocess exited with status 1
```

_Originally posted by @harshad16 in https://github.com/thoth-station/adviser/issues/2401#issuecomment-1337020238_

## Acceptance criteria

- [x] pause prescription refresh job until this is solved
  - [x] https://github.com/thoth-station/thoth-application/pull/2722
  - [x] ~~re-enable the ones that are not affected? No~~
- [x] close all outstanding prescription PRs as they do not meet the schema requirements
- [x] Fix prescriptions-refresh-job: https://github.com/thoth-station/prescriptions-refresh-job/issues/205
- [x] Fix the currently offending prescriptions in the repo: https://github.com/thoth-station/prescriptions/pull/38952
- [ ] re-enable prescription refresh job
- [ ] verify it is working: receive and merge updated prescriptions
- [ ] new release of prescriptions and adviser

Related work:
- [x] #2391
- [x] https://github.com/thoth-station/prescriptions/issues/8

**Comment by VannTen** [comment]
Should we delete invalid prescriptions completely ? With the pre-commit hooks working it should be quite easy to get a list of offending files.

**Comment by VannTen** [comment]
/assign
(I'm doing some stuff around this)
