### ISSUE TITLE
Error when resolving a TF stack

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#531]
**Describe the bug**

```python
2019-11-26 14:24:52,225 [23911] INFO     thoth.adviser.resolver:303: Resolving direct dependencies
2019-11-26 14:24:52,839 [23911] INFO     thoth.adviser.resolver:544: Hold tight, Thoth is computing recommendations for your application...
2019-11-26 14:24:55,012 [23911] INFO     thoth.adviser.resolver:609: Pipeline reached a new final state, yielding pipeline product with a score of 0
2019-11-26 14:25:00,574 [23911] INFO     thoth.adviser.resolver:609: Pipeline reached a new final state, yielding pipeline product with a score of 0
2019-11-27 14:32:48,217 [23911] ERROR    thoth.adviser.run:81: Adviser raised exception: Package ('absl-py', '0.8.1', 'https://pypi.org/simple') cannot be added to unresolved dependencies, candidate ('absl-py', '0.8.1', 'https://pypi.org/simple') is already present
Traceback (most recent call last):
  File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/run.py", line 65, in subprocess_run
    report: Union[DependencyMonkeyReport, Report] = resolver.resolve(with_devel=True)
  File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/resolver.py", line 641, in resolve
    for product in self.resolve_products(with_devel=with_devel):
  File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/resolver.py", line 606, in resolve_products
    for final_state in self._do_resolve_states(with_devel=with_devel):
  File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/resolver.py", line 573, in _do_resolve_states
    final_state = self._expand_state(beam, to_expand_state)
  File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/resolver.py", line 533, in _expand_state
    self._run_steps(beam, state, *combination_package_versions)
  File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/resolver.py", line 258, in _run_steps
    new_state.add_unresolved_dependency(package_version.to_tuple())
  File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/state.py", line 80, in add_unresolved_dependency
    f"Package {package_tuple!r} cannot be added to unresolved dependencies, "
AssertionError: Package ('absl-py', '0.8.1', 'https://pypi.org/simple') cannot be added to unresolved dependencies, candidate ('absl-py', '0.8.1', 'https://pypi.org/simple') is already present
2019-11-27 14:32:48,539 [23911] INFO     thoth.analyzer.cli:122: Writing results to 'output.json'
```

**To Reproduce**

Run adviser with the following Pipfile:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
tensorflow = "*"

[requires]
python_version = "3.6"

[pipenv]
allow_prereleases = false
```

**Expected behavior**

No error is raised.

**Comment by fridex** [comment]
Fixed, the testsuite has test for this case.
