### ISSUE TITLE
Locked requirements are optional workflow parameter

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#806]
**Describe the bug**

I'm unable to schedule adviser workflow for project that has no Pipfile.lock as ``THOTH_ADVISER_REQUIREMENTS_LOCKED`` is a required adviser workflow parameter.

**To Reproduce**

Use thamos advise in a project that has no Pipfile.lock present in the directory.

**Expected behavior**

Workflow should be scheduled.

**Additional context**

```
2020-02-12 09:19:09,071  29 ERROR    thoth.user_api.openapi_server:1891: Exception on /api/v1/advise/python [POST]
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
  | return cors_after_request(app.make_response(f(*args, **kwargs)))
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 184, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
  | return function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
  | return function(**kwargs)
  | File "/opt/app-root/src/thoth/user_api/api_v1.py", line 326, in post_advise_python
  | response, status = _do_schedule(parameters, _OPENSHIFT.schedule_adviser, output=Configuration.THOTH_ADVISER_OUTPUT)
  | File "/opt/app-root/src/thoth/user_api/api_v1.py", line 792, in _do_schedule
  | return {"analysis_id": runner(**parameters, **runner_kwargs), "parameters": parameters, "cached": False}, 202
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1624, in schedule_adviser
  | "workflow_parameters": workflow_parameters,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1217, in _schedule_workflow
  | return workflow(**parameters)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 341, in submit_adviser_workflow
  | workflow_namespace=self.openshift.backend_namespace,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 279, in submit_workflow_from_template
  | workflow_namespace or namespace, workflow, parameters=workflow_parameters
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 222, in submit_workflow
  | raise WorkflowError(f"Missing required workflow parameter {p.name}")
  | thoth.common.exceptions.WorkflowError: Missing required workflow parameter THOTH_ADVISER_REQUIREMENTS_LOCKED
```

**Comment by pacospace** [comment]
But it is provided in https://github.com/thoth-station/adviser/blob/9df98dff14d7efce5a55265cecba614460546446/workflows/templates/advise-template.yaml#L19 which is coming from https://github.com/thoth-station/adviser/blob/9df98dff14d7efce5a55265cecba614460546446/openshift/adviser-template.yaml#L27. I took parameters from https://github.com/thoth-station/adviser/blob/master/openshift/job-adviser-template.yaml

**Comment by pacospace** [comment]
In which namespace adviser is scheduled?

**Comment by fridex** [comment]
> In which namespace adviser is scheduled?

Stage.

> But it is provided in

There is missing a default value that would make it optional (as it is not required from the user side to submit also the lock file).

**Comment by pacospace** [comment]
Default value should be an empty string?

**Comment by fridex** [comment]
> Default value should be an empty string?

Yes, that should work as expected.

**Comment by pacospace** [comment]
```
---> Running application from script (app.sh) ...
2020-02-12 10:35:09,615   1 INFO     thoth.adviser:160: Version: 0.7.3
2020-02-12 10:35:09,667   1 WARNING  thoth.common.config.runtime_environment:75: Unknown configuration entry in the configuration file ipython with value {}
2020-02-12 10:35:09,792   1 CRITICAL root:101: Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/thoth/python/pipfile.py", line 415, in from_string
    parsed = json.loads(pipfile_content)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "thoth-adviser", line 680, in <module>
    __name__ == "__main__" and cli()
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "thoth-adviser", line 409, in advise
    requirements, requirements_locked, runtime_environment
  File "thoth-adviser", line 103, in _instantiate_project
    if requirements_locked
  File "/opt/app-root/lib/python3.6/site-packages/thoth/python/pipfile.py", line 417, in from_string
    raise PipfileParseError("Failed to parse provided Pipfile.lock") from exc
thoth.python.exceptions.PipfileParseError: Failed to parse provided Pipfile.lock
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by fridex** [comment]
Related: https://github.com/thoth-station/common/pull/680 https://github.com/thoth-station/common/pull/685

**Comment by fridex** [comment]
Fixed in the linked PRs above.
